### ISSUE TITLE
TLD CT "Enable Console"

### ISSUE THREAD

**Issue by ghost** [sub1to/cheat_tables#1]
Hi
Can you update the enable console cheat for the long dark game?

**Comment by sub1to** [comment]
Hey,
I tried to update it, but it won't work anymore. It seems TLD uses a new method to load assets, which I'm having a hard time finding in memory (due to the use to templates).
You can use this instead https://github.com/FINDarkside/TLD-Developer-Console

**Comment by ghost** [comment]
hmm, yes I know the Developer Console mode, but since I am using windows 8, .Net Framework 4.8 is not supported and MelonLoader gives an error and does not open.

But thank you for the anwser bro :) good day :)
Allah save you :)
